version: '3.8'

services:
  mongodb:
    image: mongodb/mongodb-community-server:7.0.5-ubi9
    container_name: solplay_mongodb
    hostname: mongodbhost
    user: root
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Quartup!01
      MONGO_INITDB_DATABASE: solplay_almacen
    volumes:
      - ./data/configdb:/data/configdb
      - ./data/db:/data/db
      - ./certs:/certs 
    ports:
      - "27017:27017"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8880:8880"
    environment:
      - NODE_ENV=production
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=Quartup!01
      - MONGO_HOST=mongodbhost
      - MONGO_PORT=27017
      - MONGO_DB=solplay_almacen
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80" # Mapea el puerto 80 del contenedor al 5173 del host
    environment:
      - VITE_API_BASE_URL=http://localhost:8880
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  node_modules:

networks:
  app-network:
    driver: bridge
